import type { RegionName, VisualLayer } from "./types";

export const REGION_ORDER: RegionName[] = [
  "BG_IMAGE",
  "CHAR_BG",
  "BG_GRADIENT",
  "BG_VIGNETTE",
  "PROGRESS_BAR",
  "POSTER_ROW",
  "AUDIO_VISUALIZER",
  "SUBTITLE_BOX",
  "WATERMARK_ROW",
];

export const REGION_LAYER_MAP: Record<RegionName, VisualLayer> = {
  BG_IMAGE: 3,
  CHAR_BG: 2,
  BG_GRADIENT: 3,
  BG_VIGNETTE: 3,
  PROGRESS_BAR: 1,
  POSTER_ROW: 2,
  AUDIO_VISUALIZER: 2,
  SUBTITLE_BOX: 1,
  WATERMARK_ROW: 1,
};

export const REGION_LABELS: Record<RegionName, string> = {
  BG_IMAGE: "BG_IMAGE",
  CHAR_BG: "CHAR_BG",
  BG_GRADIENT: "BG_GRADIENT",
  BG_VIGNETTE: "BG_VIGNETTE",
  PROGRESS_BAR: "PROGRESS_BAR",
  POSTER_ROW: "POSTER_ROW",
  AUDIO_VISUALIZER: "AUDIO_VISUALIZER",
  SUBTITLE_BOX: "SUBTITLE_BOX",
  WATERMARK_ROW: "WATERMARK_ROW",
};
